language: ruby
before_script:
  - RAILS_ENV=test bin/rails db:migrate
script:
  - CODECLIMATE_REPO_TOKEN=7535825abf3b0f9ee19871f862f6f7fc4252ba1e8a737b623e6bfd258e46cc5c bundle exec rake
  - bundle exec codeclimate-test-reporter
